fs: ecryptfs: readdir: constify actor
actor is a constant in dir_context struct and
because of that we run into following build failure:
----------
fs/ecryptfs/file.c: In function ‘ecryptfs_readdir’:
fs/ecryptfs/file.c:130:2: error: assignment of read-only member ‘actor’
make[2]: *** [fs/ecryptfs/file.o] Error 1
make[1]: *** [fs/ecryptfs] Error 2
make: *** [fs] Error 2
----------

This fix is based on commit: b2497fc([readdir] constify ->actor)

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>

Used commit: https://github.com/dwander/Linaro-base/commit/4be5c6a45a26cdfa7f6ad4a3c01cb69781f37535